# coding=utf-8
"""
API Constants
"""

CLONE = 'clone'
REQ_NEW = 'new'
REQ_APPROVED = 'approved'
REQ_ACTIVE = 'active'
REQ_EXPIRY = 'expired'

OVERRIDE_READONLY_DATA = 'OVERRIDE_READONLY'
DO_NOT_OVERRIDE_PROVISION_DETAILS = 'DO_NOT_OVERRIDE_PROVISION_DETAILS'
