# coding=utf-8
"""
    DB Constants
"""
from crams.lang_utils import reverse_dict
from crams.settings import VICNODE_APPROVER_ROLE, NECTAR_APPROVER_ROLE

__author__ = 'rafi m feroze'

JSON_APPROVER_STR = 'approver'


# SystemIds
NeCTAR_UUID = 'NeCTAR_UUID'
NeCTAR = 'NeCTAR'


# Contact Role
APPLICANT = 'Applicant'


# Request Status Codes
REQUEST_STATUS_NEW = 'N'
REQUEST_STATUS_SUBMITTED = 'E'
REQUEST_STATUS_UPDATE_OR_EXTEND = 'X'
REQUEST_STATUS_APPROVED = 'A'
REQUEST_STATUS_DECLINED = 'R'
REQUEST_STATUS_PROVISIONED = 'P'
REQUEST_STATUS_UPDATE_OR_EXTEND_DECLINED = 'J'
REQUEST_STATUS_LEGACY_SUB = 'L'
REQUEST_STATUS_LEGACY_APPROVED = 'M'
REQUEST_STATUS_LEGACY_DECLINED = 'O'

LEGACY_STATES = [REQUEST_STATUS_LEGACY_DECLINED,
                 REQUEST_STATUS_LEGACY_APPROVED, REQUEST_STATUS_LEGACY_SUB]
NON_ADMIN_STATES = [REQUEST_STATUS_NEW, REQUEST_STATUS_SUBMITTED,
                    REQUEST_STATUS_UPDATE_OR_EXTEND, REQUEST_STATUS_LEGACY_SUB]
APPROVAL_STATES = [REQUEST_STATUS_APPROVED, REQUEST_STATUS_LEGACY_APPROVED]
NEW_REQUEST_STATUS = [REQUEST_STATUS_NEW, REQUEST_STATUS_SUBMITTED]
DECLINED_STATES = [
    REQUEST_STATUS_DECLINED,
    REQUEST_STATUS_UPDATE_OR_EXTEND_DECLINED,
    REQUEST_STATUS_LEGACY_DECLINED]
ADMIN_STATES = APPROVAL_STATES + DECLINED_STATES + [REQUEST_STATUS_PROVISIONED]


# funding Body
FUNDING_BODY_NECTAR = 'NeCTAR'
FUNDING_BODY_VICNODE = 'VicNode'
# Funding Body Role Map
ROLE_FB_MAP = {
    NECTAR_APPROVER_ROLE: FUNDING_BODY_NECTAR,
    VICNODE_APPROVER_ROLE: FUNDING_BODY_VICNODE
}
FB_ROLE_MAP_REVERSE = reverse_dict(ROLE_FB_MAP)
